teleop_gui:
  ros__parameters:
    default_robot_ip: 192.168.1.211
    default_reverse_ip: 192.168.1.10
    ur_type: ur5
    default_input_type: joy
    default_gripper_type: robotiq
    default_joy_profile: auto
    joy_profiles:
    - auto
    - xbox
    - ps5
    - generic
    default_mediapipe_input_topic: /d435/camera/color/image_raw
    default_mediapipe_camera: d435
    default_mediapipe_camera_serial_number: '327122070172'
    mediapipe_camera_options:
    - d435
    - d455
    - oakd
    - camera
    realsense_d435_serial_number: ''
    realsense_d455_serial_number: ''
    default_collector_global_camera_model: d455
    default_collector_global_camera_serial_number: '146222254305'
    default_collector_wrist_camera_model: oakd
    default_collector_wrist_camera_serial_number: ''
    default_inference_global_camera_source: realsense
    default_inference_global_camera_model: d455
    default_inference_global_camera_serial_number: '146222254305'
    default_inference_wrist_camera_source: oakd
    default_inference_wrist_camera_model: oakd
    default_inference_wrist_camera_serial_number: ''
    camera_driver_options:
    - realsense
    - oakd
    default_camera_driver: realsense
    default_global_camera_source: realsense
    default_wrist_camera_source: oakd
    realsense_enable_depth: false
    oakd_enable_depth: false
    default_hdf5_output_dir: /home/rvl/collect_datasets_ws/data
    default_hdf5_filename: libero_demos.hdf5
