teleop_gui:
  ros__parameters:
    default_robot_ip: 192.168.1.211
    default_reverse_ip: 192.168.1.10
    ur_type: ur5
    default_input_type: joy
    default_gripper_type: robotiq
    default_joy_profile: auto
    joy_profiles:
    - auto
    - xbox
    - ps5
    - generic
    default_mediapipe_input_topic: /camera/camera/color/image_raw
    camera_driver_options:
    - realsense
    - oakd
    default_camera_driver: realsense
    default_global_camera_source: realsense
    default_wrist_camera_source: oakd
    default_hdf5_output_dir: /home/rvl/collect_datasets_ws/data
    default_hdf5_filename: libero_demos.hdf5
    home_joint_positions:
    - 1.4938936233520508
    - -2.1434758345233362
    - 1.7811594009399414
    - -1.2176945845233362
    - -1.5835722128497522
    - 1.5020173788070679
    home_zone_translation_min_m:
    - 0.04
    - 0.04
    - 0.04
    home_zone_translation_max_m:
    - 0.08
    - 0.08
    - 0.08
    home_zone_rotation_min_deg:
    - 5.0
    - 5.0
    - 5.0
    home_zone_rotation_max_deg:
    - 10.0
    - 10.0
    - 10.0
